# Configuration file for Vision Utilities
vlm:
  llm_mode: "ollama"  # Options: "ollama", "openai"
  model: "gemma3_12b" # Options: "GPT-4o", "gemma3:270m", "gemma3:4b", "gemma3_12b" etc.
  max_tokens: 500
